#!/usr/bin/env bash
# launcher script for recentchanges			recentchanges v5.0		05/22/2026
app_install="/usr/local/save-changesnew"
. "$app_install"/versionquery
. "$app_install"/validprogram.sh
. "$app_install"/rntchangesfunctions
res=1	;	USR=$(whoami)
if [[ "$1" = "-v" ]]; then get_vrn $1 ; elif [[ "$1" = "--help" ]] || [[ "$1" = "-h" ]] || [[ "$1" = "help" ]] || [[ "$1" = "-help" ]]; then get_vrn $1; fi
if [ $USR != "root" ]; then
    setup_exports $1
    echo "Please enter your root password below"
    #sudo -k
    # exec sudo XDG_CONFIG_HOME="$XDG_CONFIG_HOME" LAUNCHED_NON_ROOT="$LAUNCHED_NON_ROOT" -- "$0" $USR "$PWD" $1 "$2" $3
    #su - root -s /bin/bash -c 'export XDG_CONFIG_HOME="$1" ; export LAUNCHED_NON_ROOT="$2" ; exec "$3" "$4" "$5" "$6" "$7" "$8"' _ "$XDG_CONFIG_HOME" "$LAUNCHED_NON_ROOT" "$0" "$USR" "$PWD" "$1" "$2" "$3"
    su - -c "export LAUNCHED_NON_ROOT='$LAUNCHED_NON_ROOT' ; '$0' $USR '$PWD' $1 '$2' $3"
    res=$?
    output_results
fi
if [[ -z "$LAUNCHED_NON_ROOT" ]]; then
    echo query and text editor cant be run as root. comment out this line if always run as root && exit 0
    setup_exports $1
    python3 "$app_install"/rntchanges.py $USR "$PWD" "$@"
    res=$?
    output_results
fi

python3 "$app_install"/rntchanges.py "$@"

