#!/bin/bash
# Clear cache from gpgs              08/23/2025 
. /usr/share/porteus/porteus-functions
get_colors
. /usr/local/save-changesnew/save-changesnewfnts
if [[ $(whoami) != "root" ]]; then su - -c "/usr/local/save-changesnew/clearcache `whoami`" ; exit ; fi 
USR="$1"
[[ -z "$USR" ]] && USR="guest"
patterns=(
    'caches'
    'cache2'
    'Cache2'
    '\.cache'
    'share/Trash'
	"/home/$USR/Downloads/rntfiles"
	"/home/$USR/\.local/state/wireplumber"
    '/usr/share/mime/application'
    '/usr/share/mime/text'
    '/usr/share/mime/image'
	'release/cache'
    '/usr/local/save-changesnew/flth.csv'
) 
clearf() {
if [ -z "${patterns+x}" ]; then patterns=() ; fi
patterns+=("\/home\/'\"\${2}\"'\/Downloads\/rntfiles") # Add literal here ${2}
patterns+=("\/home\/'\"\${2}\"'\/\.local\/state\/wireplumber")
for pat in "${patterns[@]}"; do lno=$(grep -Fn "sed -i '/$pat/d'" "$flth" | cut -d: -f1) ; if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi ; done
}
efile="/usr/local/bin/recentchanges"			;	pydbpst="/usr/local/save-changesnew/recent.gpg"
email="john.doe@email.com"					;	flth="/usr/local/save-changesnew/flth.csv"	
[[ -n "$2" ]] && { clearf && echo "Filter hits cleared."; exit; }

