#!/bin/bash
# bash math     db v3.0                07/24/2025
comp() {
p=60
#echo "scale=1; $1 /$p" | bc
w=".0"$(( $1 * 166667 ))
if [ $1 -gt 5 ]; then
    w="."$(( $1 * 166667 ))
fi
qtn=$(( $1 / p ))
#Its less than 60 seconds
if [ "$qtn" == "0" ]; then
    qtn=$(printf '%.3s\n' $w)
fi
#It could have a remainder
if [ $1 -gt $p ]; then
    if [ ! $(( $1 % p )) -eq 0 ]; then
		x=$1
		j=$qtn

		#We dont know if it divides by 60
		while [ $x -gt 0 ]; do
			rem=$x
			x=$(( $x - $p ))

			if [ $x -eq 0 ]; then
				rem=0
				break
			fi
			if [ $x -lt 0 ]; then
				break
			fi
		done
		if [ ! $rem -eq 0 ]; then
			decmn=".0"$(( rem * 166667 ))
		fi
		if [ $rem -gt 5 ]; then
			decmn="."$(( rem * 166667 ))
		fi
		qtn=$( printf '%.2f\n' $j$decmn)
	fi
fi
}
