#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
atmp="$1" ; SORTCOMPLETE="$2" ; ofile="$3" ; checkSUM="$4" ; cdiag="$5" 
fmt="%Y-%m-%d %H:%M:%S"
rout="$atmp/haloop1_${RANDOM}$$_tmp.log" ; slog="$atmp/haloop2_${RANDOM}$$_tmp.log" ; cerr="$atmp/haloop3_${RANDOM}$$_tmp.log" ; TMPCOMPLETE="$atmp/haloop4_${RANDOM}$$_tmp.log"
declare -a collisions=()
#mapfile -t ref_lines < "$ofile"
hablk "null" $TMPCOMPLETE
