#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
	#cFILE=$(echo "$p" | sed -n 's/[^"]*"\(.*\)".*/\1/p')		
	#cfile=$(echo "$p" | perl -nE 'say $1 if /"((?:[^"\\]|\\.)*)"/')   # for " infilenm
	#cfile=$(echo "$p" | perl -nE '
	#  if (/"((?:[^"\\]|\\.)*)"/) {
	#	(my $s = $1) =~ s/\\(.)/$1/g;  # unescape backslash-escaped chars
	#	say $s;
	#  }
	#')
atmp="$1"
SORTCOMPLETE="$2"
ofile="$3"
checkSUM="$4"
rout="$atmp/haloop1_${RANDOM}$$_tmp.log"
tfile="$atmp/haloop2_${RANDOM}$$_tmp.log"
#mapfile -t ref_lines < "$ofile" # Load the reference file into memory (for faster grep)
#for line in "${ref_lines[@]}"; do if [[ "$line" == *"\"$y\""* ]]; then found_line="$line" ; fi ; done
#	
while IFS= read -r p || [ -n "$p" ]; do
	found_line=""
	cFILE=$(perl -nE 'say $1 if /"((?:[^"\\]|\\.)*)"/' <<< "$p")  
	y="$( escape "$cFILE")"
	current_ln="${p//\"$y\"/}"
	current_ln="$(echo "$current_ln" | xargs)"
    in=$(echo "$current_ln" | cut -d " " -f3)
    if [ -n "$in" ] && [ "$in" -ge 0 ] 2>/dev/null; then
		found_line="$(tac "$ofile" | grep -F -m1 "\"$y\"")"
		if [ -n "$found_line" ]; then
			sline="$found_line"
			original_ln="${sline//\"$y\"/}"
			original_ln="$(echo "$original_ln" | xargs)" 
			cFILE="$(unescf "$cFILE")"
			oin=$(echo "$original_ln" | cut -d " " -f3)
			if [ -n "$oin" ] && [ "$oin" -ge 0 ] 2>/dev/null; then
				omt=$(echo "$original_ln" | cut -d " " -f1-2)
				oat=$(echo "$original_ln" | cut -d " " -f4-5) 
				org=$(echo "$original_ln" | cut -d " " -f6)
				t=$(date -d "$oat" +%s 2>/dev/null)   
				dt=$(echo "$current_ln" | cut -d " " -f1-2)
				cat=$(echo "$current_ln" | cut -d " " -f4-5) 
				cs=$(echo "$current_ln" | cut -d " " -f6)
				k=$(date -d "$cat" +%s 2>/dev/null)
				if [ "$dt" == "$omt" ]; then
					if [ "$checkSUM" == "true" ]; then
						if [ -n "$t" ] && [ -n "$k" ]; then
							if [ -n "$org" ] && [ -n "$cs" ] && [ -f "$cFILE" ]; then
								os=$(echo "$original_ln" | cut -d " " -f7-)
								csze=$(echo "$current_ln" | cut -d " " -f7-)
								if [ -n "$csze" ]; then
									if [ "$org" != "$cs" ]; then
										a_checksum=$(md5sum "$cFILE" | awk '{print $1}') 
										a_mod=$(stat --format=%Y "$cFILE")
										afrm=$(date -d "@$a_mod" +"%Y-%m-%d %H:%M:%S")
										if [ -n "$os" ] && [ -n "$afrm" ]; then
											if [ "$afrm" == "$dt" ]; then
												echo "Csumc $dt $y"| tee -a "$rout" >> "$tfile"| tee -a /tmp/cerr; csm="true"	
											else
												if [ "$a_checksum" != "$cs" ] && [ "$cdiag" == "true" ]; then
													echo "File changed during the search. ${y} at ${afrm}. Size was $os, now $fs. " >> /tmp/scr
												elif [ "$a_checksum" != "$cs" ]; then
													echo "File changed during search ${y}. File likely changed. system cache item." >> /tmp/scr
												fi
											fi	
										fi
									else
										stealth "$cFILE" $os $csze "$y" $cdiag "csum"
									fi
								fi
							fi
						fi
					fi
				else
					if (( oin != in )); then
						if [ "$checkSUM" == "true" ]; then
							if [ -n "$org" ] && [ -n "$cs" ]; then
								if [ "$org" == "$cs" ]; then
									echo "Overwrt $dt $y" | tee -a $rout >> "$tfile"
								else
									os=$(echo "$original_ln" | cut -d " " -f7-)
									csze=$(echo "$current_ln" | cut -d " " -f7-)
									if [ -n "$t" ] && [ -n "$k" ]; then
										if [ -n "$csze" ]; then stealth "$cFILE" $os $csze "$y" $cdiag ;fi
									fi
									echo "Replaced $dt $y" | tee -a $rout >> "$tfile"
								fi
							fi
						else
							echo "Replaced $dt $y" | tee -a $rout >> "$tfile"
						fi
					else
						if [ "$checkSUM" == "true" ]; then
							if [ -n "$org" ] && [ -n "$cs" ]; then
								if [ "$org" != "$cs" ]; then
									os=$(echo "$original_ln" | cut -d " " -f7-)
									csze=$(echo "$current_ln" | cut -d " " -f7-)
									if [ -n "$t" ] && [ -n "$k" ]; then
										if [ -n "$csze" ]; then stealth "$cFILE" $os $csze "$y" $cdiag ;fi
									fi
									echo "Modified $dt $y" | tee -a $rout  >> $tfile
								else
									echo "Touched $dt $y" | tee -a $rout >> $tfile
								fi
							fi
						else
							echo "Modified $dt $y" | tee -a $rout >> $tfile
						fi
					fi
				fi	
			fi
		fi
	fi
done < "$SORTCOMPLETE"
unset IFS
