#! /usr/bin/env bash

oldpid() {
local res=0
if [[ -f $1 ]]; then
    IFS='|' read -r stored_pid stored_start < $1
    current_start="$(ps -o lstart= -p "$stored_pid")"
    if [[ -n "$current_start" ]]; then
        if [ "$current_start" = "$stored_start" ]; then
            if ! kill -- -$stored_pid; then
                echo "failed to close old pid $stored_pid $stored_start"
                res=1
            fi
        fi
    fi
    rm -f $1
fi
return $res
}

minspan() {
local first last span
local first_epoch last_epoch
if (( $3 > $2  )); then
    if [ -s "$1" ]; then
        first=$(awk 'NR==1 {print $1, $2}' "$1")
        last=$(awk 'END {print $1, $2}' "$1")
        first_epoch=$(date -d "$first" +%s 2>/dev/null)
        last_epoch=$(date -d "$last" +%s 2>/dev/null)
        if [ -n "$first_epoch" ] && [ -n "$last_epoch" ]; then
            span=$((last_epoch - first_epoch))
            if [ "$span" -ge "$3" ]; then
                : > "$1"
            fi
        else
            log_date=$(date +"$fmt")
            log_lineout "true" $4 "$log_date" "minspan failed to parse time invalid format unable to trim continuing"
        fi
    fi
elif (( $3 != 0 )); then
    : > "$1"
fi
}

phandle() {
# return 1 to process the event
# return 0 skip file
local curr_size mod_time c_time key src

read -r curr_size mod_time c_time < <(find "$o" -maxdepth 0 -printf '%s %T@ %C@\n' 2>/dev/null)
[[ -z "$c_time" ]] && return 0

src="${mvfrm_pending[$cookie]}"
# the unusual. if src is in it it would be rare.
if [[ -n "$src" && -v create_pending["$src"] ]]; then
    key="${create_pending[$src]}"
    unset 'create_pending[$src]'
    unset 'mvfrm_pending[$cookie]'
    rm -- "$datadict/$key" 2>/dev/null
    res=$?
    log_lineout $debug_log $debug_file "$log_date" "inotify MOVED_TO unusual src was in create_pending on move after created file. src: $src dest or file: $o"
    if $res; then
        return 1
    else
        return 0
    fi
    

# the usual. firefox and others normal for downloaded file where created src or $o matches the move dest or $o.
elif [[ -v create_pending["$o"] ]]; then
    key="${create_pending[$o]}"
    unset 'create_pending[$o]'
    if rm -- "$datadict/$key" 2>/dev/null; then
        return 1
    else
        return 0
    fi

else

    # does it look like a creation event?
    log_lineout $debug_log $debug_file "$log_date" "inotify MOVED_TO did not have a creation event checking if ctime >= mtime for file: $o"
    [[ -z "$src" ]] && log_lineout $debug_log $debug_file "$log_date" "inotify MOVED_TO did not have a MOVED_FROM event: $o"

    if [[ "$c_time" < "$mod_time" ]] || [[ "$c_time" < "$STRTTIME" ]]; then
        log_lineout $debug_log $debug_file "$log_date" "inotify MOVED_TO it was a regular move. skipping.. file: $o"
        return 0

    fi
fi

return 1
}

