#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/save-changesnewfnts
fmt="%Y-%m-%d %H:%M:%S"
prefix=mainloop1
prefixt=mainloop2
prefixth=cache1

atmp="$1"
checkSUM="$2"
[[ "$3" = "batch2" ]] && prefix=mainloop3 && prefixt=mainloop4 && prefixth=cache2
CACHE_F="$4"
deltadiff=$5
CSZE=$6
shift 6

# $atmp "false" "main" "batch2"
SORTCOMPLETE="${atmp}/${prefix}_${RANDOM}$(rand_alpha)$$_tmp.log"
NFS="${atmp}/${prefixt}_${RANDOM}$(rand_alpha)$$_tmp.log"
CACHE="${atmp}/${prefixth}_${RANDOM}$(rand_alpha)$$_tmp.log"

if [ "$CSZE" -ge 0 ] 2>/dev/null; then
    for f in "$@"; do

	    sblk "$f" $SORTCOMPLETE $NFS $checkSUM $CSZE $CACHE $deltadiff
    done
else
	echo "mainloop Incorrect arguments supplied"
fi

