#!/bin/bash                      
# rename them in batches so filename conflicts are checked first. before doing anything  
#  Usage: rename all _uid_  .bak to .xzm.    -r flag to reverse .xzm to .bak Dec 20, 2025
. /usr/share/porteus/porteus-functions
get_colors
. /usr/local/save-changesnew/mergemodulesfunctions
if [[ $(whoami) != "root" ]]; then echo Please run script as root; exit; fi
renmmdl "_uid_" $1
