#!/bin/bash    
# rename them in batches so filename conflicts are checked first. before doing anything  
# Usage: rename all L_uid_   .bak to .xzm. -r flag to reverse .xzm to .bak Apr 06, 2026
. /usr/share/porteus/porteus-functions
get_colors
. /usr/local/save-changesnew/mergemodulesfunctions
if [[ $(whoami) != "root" ]]; then echo Please run script as root; exit; fi
renmmdl "L_uid_" $1
