#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/save-changesnewfnts
atmp="$1"
IN="$2"
# folder="$3"
pf="$4" #Prefix
tout="${atmp}/${pf}1_${RANDOM}$(rand_alphauid)$$_tmp.log"  
cp $IN $tout
#while read -r -d '' x; do y="${x#"$folder"}" ; printf "%s\0" "$y" >> "$tout" ; done < $IN
# y="$( escf "$y")"
# make relative escape chars and convert to \0

