#!/bin/bash
shopt -s nullglob										# 02/25/2026
. /usr/local/save-changesnew/rntchangesfunctions
atmp=/tmp/ztmp$$ 					;	ch=/mnt/live/memory/images/
fmt="%Y-%m-%d %H:%M:%S"	;	xdata3=$atmp/db_log.log
xdata=$atmp/log.log					;	SORTCOMPLETE=$atmp/list_complete_sorted.txt
md="$1"									;	systemf=$atmp/filelist
# TMPF=$atmp/structure
mkdir $atmp

y=50

dedupe_first_path_z() {
	local in_file=$1
	local out_file=$2
	local rec key
	local i
	local meta_fields=9
	declare -A seen=()

	: > $out_file
	while IFS= read -r -d '' rec; do
		key="$rec"
		for ((i=0; i<meta_fields; i++)); do
			[[ "$key" == *" "* ]] || break
			key="${key#* }"
		done
		[[ ${seen["$key"]+_} ]] && continue
		seen["$key"]=1
		printf '%s\0' "$rec" >> "$out_file"
	done < "$in_file"
}

: > $xdata3
: > $systemf

for folder in "$ch"{003..000} "$ch"{003..000}-*; do

	[ ! -d "$folder" ] && continue
	find "$folder" -not -type d -printf '%T@ %A@ %C@ %i %M %s %u %g %m /%P\0' >> $systemf
	if [[ "$folder" == "$ch"000 ]]; then continue ; fi # dont hash kernel firmware

	#binaries                  # ! -path '*/usr/share/*' 
		for subdir in bin usr/bin usr/sbin etc sbin opt/porteus-scripts; do
			dir="$folder/$subdir"
			if [ -d "$dir" ]; then
				# find "$dir" -type f -executable -not -type d '%T@ %A@ %C@ %i %s %u %g %m %p\0' > $xdata   # have to remove $folder
				find "$folder"  -path "$dir/*" -not -type d -executable -printf '%T@ %A@ %C@ %i %M %s %u %g %m /%P\0' > $xdata
				cat "$xdata" >> "$xdata3"
			fi
		done

	# configs
		for subdir in $folder/etc $folder/home $folder/root; do
			if [ -d "$subdir" ]; then
				find "$folder" -not -type d -path "$subdir/*" -printf '%T@ %A@ %C@ %i %M %s %u %g %m /%P\0' > $xdata
				cat "$xdata" >> "$xdata3"
			fi
		done

	# *.so*
		for subdir in $folder/lib $folder/lib64 $folder/usr/lib $folder/usr/lib64 $folder/var/lib; do
			if [ -d "$subdir" ]; then
				find "$folder" -not -type d -name '*.so*' -path "$subdir/*" -printf '%T@ %A@ %C@ %i %M %s %u %g %m /%P\0' > $xdata
				cat "$xdata" >> "$xdata3"
			fi
		done
done

dedupe_first_path_z "$systemf" "$xdata"
mv "$xdata" "$systemf"

dedupe_first_path_z "$xdata3" "$xdata"
mv "$xdata" "$xdata3"

# Escape filenames
# while IFS= read -r -d '' x; do x="$( escf "$x")" ;  printf "%s\0" "$x" ; done < $systemf > $TMPF ; mv $TMPF $systemf 
sort -z -o $systemf $systemf 
sort -z -o $xdata3 $xdata3 #files to hash Already escaped
comm -z -23 $systemf $xdata3 > $xdata # all other files not hashed
## hash the selected files and convert
x=$(tr -cd '\0' < $xdata3 | wc -c) 
# y=5000 ; max_jobs=1
if [ "$md" == "mc" ]; then
	cores=$( nproc 2>/dev/null || echo 1)
	max_jobs=$(( cores > 16 ? 16 : cores ))
    y=$(( (x + max_jobs - 1) / max_jobs ))
    xargs -0 -n "$y" -P "$max_jobs" /usr/local/save-changesnew/profileloop $atmp "true" "main" "batch1"  < $xdata3
    isoutput "mainloop1*" $SORTCOMPLETE
else
    while IFS= read -r -d '' p ; do
        rblk "$p" $SORTCOMPLETE "/dev/null" "true"
    done < $xdata3
fi
#remaining dont hash but convert
x=$(tr -cd '\0' < $xdata | wc -c) 
if [ "$md" == "mc" ]; then
    y=$(( (x + max_jobs - 1) / max_jobs ))
    xargs -0 -n "$y" -P "$max_jobs" /usr/local/save-changesnew/profileloop $atmp "false" "main" "batch2"  < $xdata
    isoutput "mainloop3*" $SORTCOMPLETE
else
    while IFS= read -r -d '' p ; do
        rblk "$p" $SORTCOMPLETE "/dev/null" "false"
    done < $xdata
fi
if [[ -s $SORTCOMPLETE ]]; then
	sort -o $SORTCOMPLETE $SORTCOMPLETE
	echo "$SORTCOMPLETE"
else
	exit 6
fi
# Just get the filename
#while IFS= read -r -d '' y; do  x=$(escf "$(cut -d' ' -f9- <<< "$y")") ; printf '%s\0' "$x"; done < $xdata3 > $TMPF
#sort -z -o $TMPF $TMPF
#comm -z -23 $systemf $TMPF > $xdata # all other files not hashed
