#!/bin/bash
atmp="$1"
folder="$2"
pf="$3"
tout="${atmp}/${pf}1_${RANDOM}$$_tmp.log"  # create temp output file path using current PID
shift 3

files=("$@")

for f in "${files[@]}"; do
    t="${f#"$folder"}"
    printf "%s\0" "$t" >> "$tout"
done
