#!/bin/bash
#   NMS5                                                                            06/18/2026  v5.0
# entry point for recentchanges.
#
#   recentchanges. aka Developer buddy      recentchanges / recentchanges search
#   Provide ease of pattern finding ie what files to block we can do this a number of ways
#   1) if a file was there (many as in more than a few) and another search lists them as deleted its either a sys file or not but unwanted nontheless
#   2) Is a system file inherent to the specifc platform
#   3) intangibles ie trashed items that may pop up infrequently and are not known about
#
#   recentchanges
#           Searches are saved in /tmp
#
#           1. Search results are unfiltered
#           2. /tmp files are pulled out for clear easy to read results. Too much information makes it more difficult to interpret
#           3. rnt can be used to inverse the results and apply a filter
#
#
#   recentchanges search
#           Searches are saved in /home/{user}/Downloads
#
#           1. The search is unfiltered and a filesearch is filtered.
#           2. `rnt search` is a shortcut and inverses the results. For search it will filter the results instead of being unfiltered. For a file search it removes the filter instead as its normally filtered.
#
# Old searches can be grabbed from /tmp/{MODULENAME}_MDY_*. the limit is set by archivesrh. This is for convenience if there is no previous search it displays the
# old search for specified search criteria.
#
#  Also borrowed script features from various scripts on porteus forums
# working off of base save-changes script by
# Author: Brokenman <brokenman@porteus.org>
# Author: fanthom <fanthom@porteus.org>
. /usr/share/porteus/porteus-functions
get_colors
. /usr/local/save-changesnew/versionquery
. /usr/local/save-changesnew/validprogram.sh
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/comp
# If you want xed or featherpad to open set dspEDITOR to false
# CHANGEABLE


export backend="database" 	# default   bash 2 gpg and queries text based stable tested  
											# database   binary database faster queries 1 gpg and python (easier ha)

export email="john.doe@email.com" # default for asymmetrical gpg auth for STATPST
                                                        # asks for paraphrase and caches for 15 minutes
                                                        # leave default

export logSIZE=50 # default 50mb for persistent storage pst

export logCT=300 # Max searches to store in pst storage before removing one

export logPRF="del" # del delete and stop    what to do on max logSIZE
                                # stop leave in place
                                # rfh refresh clear and log again


export compLVL=200  # default 200mb to disable compression on logpst size

#this script
cmode="gzip"                   # default nothing. uses gzip compression level balanced. This is for recentchanges .xzm and SRC tag
                                           # xz        best compression
                                           # zstd     faster bootup
                                            # lzo      faster bootup
archivesrh=5						# How many old searches to save and rnt.xzm in /tmp(all filtered files) pulled. These can be grabbed by recentchanges search and recentchanges 
#
#SRC options
#this script
xzmname="Application$$" # What to name .xzm when using SRC and create the .xzm automatically without selecting or entering a name. mutually depedent on autooutput
autooutput="false"
#
# end this script

export tmpSRHS=7 # Default 7. for ANALYTICS. store most recent searches in /tmp try 30 and then run recentchanges query with STATPST false
                                # for hybrid analysis in diff file
                                 # also queries ie recentchanges query stats



export mMODE="mc"  # default. regular search
								   		# mc      turbo mode run the search in parallel or multiple cores.


export ANALYTICS="false" # store recent searches in /tmp       default false
                                        # gives hybrid analysis in diff file more files to compare no overhead as only checks modified
                                        # makes more sense to work off of /tmp than to decrypt everytime
                                        # for that reason you can choose /tmp or STATPST or both and recentchanges query
                                        # if you want your searches to be encrypted just use STATPST

                                        # if you start decrypting here searching there running post ops and everything else its a bad idea
                                        # for that reason I put protections in place for POSTOP

                                        # useful for quickly checking system filess
                                        # not as secure but still owned by root in /tmp but its temporary anyway and can be turned off


export STATPST="true" # persistent storage searches encrypted in /usr/local/save-changesnew for recentchanges query see logSIZE / logCT
                                    # Only overhead is gpg compression set compression to off. At large size speeds can increase by as much as 50%.
                                    # if you prefer security turn ANALYTICS false and use this

export xRC="false"	# false - default. run inotifywait for one hour to look for new files where ctime > mtime in /changes.
									# this is for downloads or copies with preserved metadata pacman slackpkg ect.
									# if false the files will still show up keep in mind the /tmp file search results are in a seperate file in /Downloads use `recentchanges search`
									# With this setting If true can bypass 1 of 2 search loops and reduce process overhead as the search is already there effectively increasing the overall speed

#Display
export ANALYTICSECT="true" # provides more feedback
                                            # total search time ect
                                            # we dont want too much output on the terminal just a slight bit more
                                            # others stats

export FEEDBACK="true"  # include find output in terminal as well ie scrolling terminal look


export dspEDITOR="xed" # false.  default dont display text editor. launch text editor?
										# featherpad
										# xed  


## Diagnostics
export checkSUM="true"	# compare file checksums for slight changes
										# slower useful if you want to check deeper level of stats
export cdiag="true"       # add extra detail like filesize in output and critical events. Also check for hash collisions.
export supbrwr="true"   # supress cache warnings on terminal from known browsers? Mozilla... ect list top of rntfuncions see rntchangesfunctions
export suppress="false"  # ..      all cdiag output to terminal except critical events

export POSTOP="false" # Diagnostics. Create file doctrine. Runs post search operation that can only be done at this time as search is relevant
                                    # more overhead so recommend off unless one off. output /Downloads
                                    #
                                    # if it is run again and a file is still there it will not run the POSTOP and the script will set POSTOP to false to itself

export proteusSHIELD="false"	# take initial hash of base modules 001-core.. ect database mode
## End Diagnostics

export MODULENAME="rntfiles"    # prefix for search result file
export logpst="/usr/local/save-changesnew/logs.gpg"
export statpst="/usr/local/save-changesnew/stats.gpg"
export pydbpst="/usr/local/save-changesnew/recent.gpg"
export ctimecache="/usr/local/save-changesnew/ctimecache.gpg"
export flth="/usr/local/save-changesnew/flth.csv"

# END CHANGEABLE
[[ "$mMODE" != "default" ]] && [[ "$mMODE" != "mc" ]] && echo incorrect mMODE && exit 
[[ "$STATPST" == "true" ]] && [[ "$ANALYTICS" == "true" ]] && { echo With STATPST cant run with ANALYTICS. for security reasons as its stored in gpg. ; } && exit
[[ "$STATPST" == "false" ]] && [[ "$backend" == "database" ]] && echo database requires STATPST && exit
if [ "$1" = "-v" ]; then get_vrn $1 ; elif [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ "$1" = "-help" ]; then get_vrn $1; fi

if (( EUID != 0 )); then
    echo "Please enter your root password below"
    sudo -k
    exec sudo /opt/recentchanges/recentchanges "$1" "$2" "$3" "$(id -un)" "$PWD"
    exit
fi

argone=${1:-noarguser}
argtwo=${2:-noarguser}

if [[ $1 == inv ]]; then
    argf="filtered"
    argone="noarguser"

elif [[ $2 == inv ]]; then
    argf="filtered"
    argtwo="noarguser"

elif [[ $3 == inv ]]; then
    argf="filtered"
fi

USR="$4"
passdir="$5"

if  ! id $USR>/dev/null 2>&1; then echo "user: $USR not found"; exit 1; fi
if [ "$4" == "" ] || [ "$5" == "" ]; then USR="guest" ; passdir=$PWD ; fi #Default user
if [ "$3" == "SRC" ]; then echo "Incorrect usage please use recentchanges SRC s , s SRC or SRC" && exit 1; fi
if [ -z "$argf" ]; then argf="bnk"; fi #Default

export DISPLAY=:0  # for tkl and root xed featherpad
export XAUTHORITY=/home/$USR/.Xauthority

if [ "$1" == "reset" ]; then
	if [ "$STATPST" == "true" ]; then
		 python3 /usr/local/save-changesnew/pstsrg.py "$0" "$pydbpst" "root" $email $mMODE $compLVL $checkSUM "true" "$logpst" "$statpst" "$ctimecache"
		ret=$?
		[[ $ret -eq 0 ]] && { remove_gpg ; exit 0 ; }
		exit 1
	else
		echo "reset requries STATPST for default or database key reset" && exit 1
	fi
elif [ "$1" == "query" ]; then
	if [ "$backend" == "default" ]; then
		[[ -z $2 ]] && THETIME="noarguser" || THETIME=$2
        /usr/local/save-changesnew/query $THETIME $USR "$passdir"
        exit
    else

        python3 /usr/local/save-changesnew/query.py "$0" $pydbpst $USR $email $mMODE $compLVL $checkSUM
        exit
    fi
fi

#VARS
# $tmp  main search tmp files from original
# $atmp  secondary tmp files from upgrade
# $atmpwork   multiprocessing tmp files so not messy
# $atmp$workdir   restricted decrypted pst file for ha. & ha multiprocessing related files
workdir=/hablk															;	workfld=/fsearch$$
tmp=/tmp/work$$														;	chxzm=/$MODULENAME.xzm
ABSENT=$tmp/tmp_absent.txt									;	atmp=/tmp/atmp$$ 
UPDATE=$tmp/save.transferlog.tmp							;	rout=$atmp/routput.tmp
RECENT=$tmp/list_recentchanges_filtered.txt				;	xdata=/logs_stats.log # dcryp log file
RECENTAPP=$tmp/list_recentapp_filtered.txt				;	xdata2=/logs.log.log
COMPLETE=$tmp/list_complete.txt								;	xdata3=$atmp$workdir/temp_log.log 
TMPOUTPUT=$tmp/list_tmp_sorted.txt 						;	tfile=$atmp$xdata
TMPCOMPLETE=$tmp/tmp_complete.txt						;	tfile2=$atmp$xdata2
RSYNCEXCL=$tmp/list_filesexclude.txt						;	tout=$atmp/toutput.tmp 
TMPOPT=$tmp/tmp_holding										;	toutnul=$atmp/toutputnul.tmp
REJECTLOG=$tmp/list_rejectsrc.txt								;	xopt=/mnt/live/tmp # spare tmp dir
FOLDERLOG=$tmp/save.totalfolders.tmp					;	log_file=/tmp/file_creation_log.txt
SORTCOMPLETE=$tmp/list_complete_sorted.txt			;	LCLMODULENAME=${chxzm:1:8}
RECENTNUL=$tmp/list_recentchanges_filterednul.txt	;	USRDIR=/home/$USR/Downloads
SVFOLDERS=$tmp/save.rncfoldersmanifest.tmp			;	SVFILES=$tmp/save.rncfilesmanifest.tmp
cdir=/tmp/dbctimecache/                                      		;   secondary=()
cerr=/tmp/cerr															;	arrreject=()
slog=/tmp/scr															;	arrfiles=()

CACHE_F="${cdir}ctimecache"
INOTIFY_CACHE="${cdir}inotify_cache"
LOCKFILE=/tmp/pblk.lock
BRAND=$(date +"MDY_%m-%d-%y-TIME_%R" | tr ':' '_')
FLBRAND=$(date +"MDY_%m-%d-%y-TIME_%R_%S" | tr ':' '_')

SRCDIR=""																	;	csm=""
dirSRC=""																	;	OLDSORTED=""

ha_total_time=""														;	logger_total_time=""
lifetime_total=""														;	lifetime_time=""
total_files=0																;   total_time=0	
cores=0																	;	max_jobs=0

diffrlt="false"															;	pstc="false"
nodiff="false"															;	samerlt="false"
syschg="false"															;	validrlt="false"
approval="true"														;	nc="false"
csum="false"															;	valid_data="true"

search="false"
filtered="false"
flsrh="false"

# /etc /home /lib /lib64 /opt /root /sbin /tmp /usr /var
F=( / )
TAIL=(-not -type d -printf '%T@ %A@ %C@ %i %M %n %s %u %g %m %p|%l\0')

mkdir $tmp
mkdir $tmp$workdir
mkdir $atmp
mkdir $atmp$workfld
mkdir $atmp$workdir
intst

if [ "$1" == "search" ]; then
    search="true"
    THETIME="$argtwo"

else    
    THETIME="$argone"
    start=$(date +%s.%N)
    [ "$THETIME" == "SRC" ] &&{ SRCDIR=$THETIME; THETIME="$argtwo"; }  # shift
    [ "$2" == "SRC" ] && SRCDIR=$2 || { [ "$2" == "SEARCH" ] || [ "$2" == "search" ]; } && echo "The SRC tag is for recentchanges only" && exit

fi

if [ "$argf" == "filtered" ]; then
    filtered="true"
fi

if [ "$THETIME" != "noarguser" ]; then
	if [ "$THETIME" -ge 0 ] 2>/dev/null; then
        argone=$THETIME
		comp $argone
		tmn=$qtn
		cyan "searching for files $2 seconds old or newer"
    else
        argone=".txt"
    	test -d "$passdir" || { echo "Invalid argument $passdir . PWD required."; exit 1; }
		cd "$passdir"  || exit
    	filename="$argtwo"
    	test -f "$filename" || { test -d "$filename" || echo no such directory file or integer; exit 1; }
    	parseflnm="${argtwo##*/}"
		if [ "$parseflnm" == "" ]; then parseflnm="$(echo "$argtwo" | sed -e 's/\/$//' -e 's@.*/@@')" ; fi
    	cyan "searching for files newer than $filename "

        if [ "$filtered" == "true" ]; then
            filtered="false"
        else
            filtered="true"
        fi
    	flsrh="true"

		ct=$(date +%s)
		fmt=$(stat -c %Y "$filename")
		ag=$(( ct - fmt ))
		comp $ag
		ag=$qtn
		MMIN=(-newer "$filename")
		CMIN=(-cmin "-$ag")
    fi
else
	argone="5" ; tmn=$argone ; cyan "searching for files 5 minutes old or newer"
fi
if [ "$tmn" != "" ]; then

	MMIN=(-mmin "-$tmn")
	CMIN=(-cmin "-$tmn")
fi
findrelavant
findfiles

if [ -s $SORTCOMPLETE ]; then

	syschg="true"

	sort -u -o  $SORTCOMPLETE $SORTCOMPLETE ; SRTTIME=$( head -n1 $SORTCOMPLETE | awk '{print $1 " " $2}') ; PRD=$SRTTIME

	merge_ctime $SORTCOMPLETE $tout $PRD
	inclusions $SORTCOMPLETE

    if [ "$flsrh" != "true" ]; then
	    s=$(date -d "$SRTTIME" "+%s")
	    if [ "$THETIME" == "noarguser" ]; then RANGE=$(( s + 300 )) ; else RANGE=$(( s + argone )) ; fi  # filter out non existant files ect
	    PRD=$(date -d "@$RANGE" +"$fmt")
	    awk -v tme="$PRD" '{ ts = $1 " " $2; if (ts <= tme) print }' $SORTCOMPLETE > $tout ; mv $tout $SORTCOMPLETE
    fi

	sort -u -o $SORTCOMPLETE $SORTCOMPLETE

	process_sort $SORTCOMPLETE $TMPOPT

    cat $TMPOPT | grep ' /tmp/' > $TMPOUTPUT
    sort -o $TMPOUTPUT $TMPOUTPUT
	sed -i '/\"\/tmp/d' $SORTCOMPLETE
	sed -i '/ \/tmp/d' $TMPOPT
	sort -o $TMPOPT $TMPOPT

    cp $TMPOPT $RECENT

    cut -d' ' -f3- $RECENT > $tout ; mv $tout $RECENT

    /usr/local/save-changesnew/filter $RECENT $USR

    logf=$TMPOPT
    if [ $filtered == "true" ]; then
        logf=$RECENT
    fi

    cd /tmp || exit
    MODULENAME=${chxzm:0:9}
    moduledir=$MODULENAME"_"$FLBRAND
    chxzmnm=$MODULENAME"manifest.txt"
    FLTOUT="/tmp"$MODULENAME"ItemsFilteredout"

    if [ "$flsrh" == "true" ]; then
	    flnm="xNewerThan_$parseflnm"
	    flnmdff="xDiffFromLast_$parseflnm"

    elif [ "$argf" == "filtered" ]; then
	    flnm="xFltchanges_"$argone
	    flnmdff="xFltDiffFromLastSearch_"$argone
    else
	    flnm="xSystemchanges"$argone
	    flnmdff="xSystemDiffFromLastSearch"$argone
    fi

    if [ "$search" == "false" ]; then
        dirSRC=/tmp  # recentchanges

        # SRC tag make .xzm from a root folder
        if [ "$SRCDIR" == "SRC" ]; then
            findrootfolder
        fi
    else
        dirSRC=$USRDIR  # recentchanges search
    fi

    difffile="$dirSRC$MODULENAME$flnmdff"

    # check for previous existing search to diff
    if [ -e "$dirSRC$MODULENAME$flnm" ]; then
        cp "$dirSRC$MODULENAME$flnm" $tmp && OLDSORTED="$tmp$MODULENAME$flnm"

    # if nothing was found
    elif [ "$flsrh" == "false" ]; then
        
        # if recentchanges search look in /tmp. 
        if [ "$search" == "true" ]; then
            if [[ -e /tmp$MODULENAME$flnm ]]; then
                cp /tmp$MODULENAME$flnm $tmp
                OLDSORTED="$tmp$MODULENAME$flnm"
            fi
        fi

        # if nothing found check in archived searches
        [[ -z $OLDSORTED ]] && hsearch

    fi

    # Reset. move old searches
    clearlogs
        
    # send tmp results to user
    if [ -s $TMPOUTPUT ]; then
        cp $TMPOUTPUT $dirSRC$MODULENAME"xSystemTmpfiles$parseflnm"
        chown $USR $dirSRC$MODULENAME"xSystemTmpfiles$parseflnm"
    fi

    # prep OLDSORT
    # possible sort?
    # sed -i '/^[[:space:]]*$/d' $OLDSORTED  # remove blank lines

    [[ -n $OLDSORTED ]] && nodiff="true" && comm -23 "$OLDSORTED" $logf > "$difffile"

    cp $logf "$dirSRC$MODULENAME$flnm"
    chown $USR "$dirSRC$MODULENAME$flnm"

    isdiff "$difffile" $TMPOPT $TMPCOMPLETE

	backend $argf
	filterhits $TMPOPT $flth
	postop $SORTCOMPLETE $0
    test -e "$difffile" && chown $USR "$difffile"

fi

#Cleanup
if [ "$ANALYTICS" == "true" ] && [ "$STATPST" == "false" ]; then 
    stmp $SORTCOMPLETE
    if [ ! -f /tmp/rc/full ]; then cyan "Search saved in /tmp"; fi
fi

test -d "$tmp" && rm -rf "${tmp:?}" 
test -d "$atmp" && rm -rf "${atmp:?}"

logic "Refer to /rntfiles_MDY folder for the previous search"
analytics
display $dirSRC "$MODULENAME$flnm"

