#!/bin/bash
# Clear cache from gpgs              08/23/2025 
. /usr/share/porteus/porteus-functions
get_colors
clearc() {
sed -i '/caches/d' $1
sed -i '/cache2/d' $1
#sed -i '/cache/d' $1
sed -i '/Cache2/d' $1
sed -i '/\.cache/d' $1
sed -i '/\share\/Trash/d' $1
sed -i '/\/usr\/share\/mime\/application/d' $1
sed -i '/\/usr\/share\/mime\/text/d' $1
sed -i '/\/usr\/share\/mime\/image/d' $1
}
decrypt(){	if ! gpg --yes -d -o $1 $2; then red "Failed to decrypt  ${2}" && rm $atmp && exit 1; fi; }
encr() { if ! gpg --yes -e -r $mail -o $2 $1; then red "Rencryption failed. Everything preserved" && rm $atmp && exit 1; fi; }
atmp=/tmp/atmp$$
efile="/usr/local/bin/recentchanges"
logpst="/usr/local/save-changesnew/logs.gpg"
statpst="/usr/local/save-changesnew/stats.gpg"
flth="/usr/local/save-changesnew/flth.csv"
email="john.doe@email.com"
xdata=$atmp/logs_stats.log
mkdir $atmp
rlt=$(sed -n 's/.*export logpst=\([^ ]*\).*/\1/p' $efile)
rltt=$(sed -n 's/.*export statpst=\([^ ]*\).*/\1/p' $efile)
mail=$(sed -n 's/.*export email=\([^ ]*\).*/\1/p' $efile)
rlt=${rlt//\"/} ; rltt=${rltt//\"/} ; mail=${mail//\"/}
if [ -z "$rlt" ] ;then rlt=$logpst; fi
if [ -z "$rllt" ]; then rltt=$statpst; fi
if [ -z "$mail" ]; then mail=$email; fi
echo $rlt
test -f $rlt || { cyan "logpst not found." && exit; }
test -f $rltt || { cyan "statpst not found." && exit; }
decrypt $xdata $rlt
clearc $xdata
encr $xdata $rlt && rm $xdata
decrypt $xdata $rltt
clearc $xdata
encr $xdata $rltt && rm $xdata
lno=$(grep -Fn "sed -i '/caches/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
lno=$(grep -Fn "sed -i '/cache2/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
lno=$(grep -Fn "sed -i '/Cache2/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
lno=$(grep -Fn "sed -i '/\.cache/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
lno=$(grep -Fn "sed -i '/share\/Trash/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
lno=$(grep -Fn "sed -i '/\/usr\/share\/mime/d'" "$flth" | cut -d: -f1)
if [[ -n $lno ]]; then sed -i "${lno}s/,[0-9]\+\$/,0/" $flth ; fi
green "Cache succesfully cleared"
rm -rf $atmp
