#!/bin/bash

# Filter modified date: 07/25/2025       SN:049BN6KZ01
#
#	Notes: has porteus 5.01 and 5.1 built in
#
# $1 first file $2 user $3 second file

## Base var exclusions

# we dont want /var/cache
sed -i '/\/var\/cache/d' $1 $3

# we dont want  /var/run
sed -i '/\/var\/run/d' $1 $3

# we dont want  /var/tmp
sed -i '/\/var\/tmp/d' $1 $3
# we dont want /var/lib/NetworkManager
sed -i '/\/var\/lib\/NetworkManager/d' $1 $3
# we dont want /var/lib/upower
sed -i '/\/var\/lib\/upower/d' $1 $3
# we dont want  /var/log
sed -i '/\/var\/log/d' $1 $3
## End base var exclusions



# we dont want /opt/porteus-scripts/
sed -i '/\/opt\/porteus-scripts/d' $1 $3
# we dont want /usr/share/mime
sed -i '/\/usr\/share\/mime/d' $1 $3
# we dont want /usr/share/glib-2.0/schemas
sed -i '/\/usr\/share\/glib-2\.0\/schemas/d' $1 $3

# Porteus 5.01
sed -i '/\/usr\/lib64\/libXc/d' $1 $3
sed -i '/\/usr\/lib64\/libudev/d' $1 $3
sed -i '/\/var\/db\/sudo\/lectured\/1000/d' $1 $3
sed -i '/\/home\/'"${2}"'\/\.config\/dolphinrc/d' $1 $3
sed -i '/\/home\/'"${2}"'\/\.config\/konsolerc/d' $1 $3
sed -i '/\/home\/'"${2}"'\/\.config\/featherpad\/fp\.conf/d' $1 $3
sed -i '/\.config\/glib-2\.0\/settings\/keyfile/d' $1 $3

# we dont want  .bash_history
sed -i '/\.bash_history/d' $1 $3
# we dont want to  .cache
sed -i '/\.cache/d' $1 $3
# we dont want .dbus
sed -i '/\.dbus/d' $1 $3
# we dont want .gvfs
sed -i '/\.gvfs/d' $1 $3
# we dont want .gconf
sed -i '/\.gconf/d' $1 $3
# we dont want to .gnupg
sed -i '/\.gnupg/d' $1 $3
# we dont want .local/share
sed -i '/\.local\/share/d' $1 $3
# we dont want xsession errors
sed -i '/\.xsession/d' $1 $3

#Inclusions from script
# $USR passed from recentchanges argument chaning into root  $3
# we dont want  USER/.config

sed -i '/\/home\/'"${2}"'\/\.config/d' $1 $3
#sed -i '/\/home\/'"${2}"'\/\.config\/save-changesnew/d' $1 $3

# we dont want   root .auth90
sed -i '/\/root\/\.auth/d' $1 $3
# we dont want  root/.config
sed -i '/\/root\/\.config/d' $1 $3
# we dont want   root .lesshst
sed -i '/\/root\/\.lesshst/d' $1 $3
# we dont want   root .xauth
sed -i '/\/root\/\.xauth/d' $1 $3

#Firefox (Only unwanted files from profile)
#sed -i '/release\/cookies\.sqlite-wal/d' $1 $3
#sed -i '/release\/sessionstore-backups/d' $1 $3
#sed -i '/release\/aborted-session-ping/d' $1 $3
#sed -i '/release\/cache/d' $1 $3
#sed -i '/release\/datareporting/d' $1 $3
#sed -i '/release\/AlternateServices\.bin/d' $1 $3
#Chromium
#sed -i '/ungoogled/d' $1 $3

#  Now we get into the important directories. Do we exclude at the risk of deleting our program? Tread carefully
#
#  Very carefully select only starting /etc/    <------  We can remove this filter if needed
#
#
# we dont want  /etc/
#sed -i '/^\/etc/d' $1 $3        <--------- including  /etc/
