#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
atmp="$1" ; SORTCOMPLETE="$2" ; ofile="$3" ; checkSUM="$4" ; cdiag="$5" ; TMPCOMPLETE="$6"
fmt="%Y-%m-%d %H:%M:%S"
rout="$atmp/haloop1_${RANDOM}$$_tmp.log" ; tfile="$atmp/haloop2_${RANDOM}$$_tmp.log"
declare -a collisions=()
#mapfile -t ref_lines < "$ofile"
hablk
