#!/bin/bash
#inotify db3 					09/14/2025
. /usr/local/save-changesnew/rntchangesfunctions
#atmp=/tmp/myfld$$
tmp_input="/tmp/inotify_input_$$.tmp"
ch="/mnt/live/memory/changes/"
log_file=$1
CACHE_F="$2"
time="$5"
checkSUM="$3"
xMODE="$4"
> "$tmp_input"
timeout "$time" inotifywait -m -r -e create -e moved_to --format '%w%f' "$ch" | while read -r o; do [[ -f "$o" ]] && if [[ "$o" != *.part ]]; then { stat --format="%Y %X %Z %i %s %U %G %a %n" "$o" 2>/dev/null; printf '\0'; } | sblk /dev/stdin "$log_file" "/dev/null" "$xMODE" ; fi ; done
fi
test -e $log_file && rm $log_file



