#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/save-changesnewfnts
atmp="$1"
IN="$2"
#SORTCOMPLETE="$3"
#NFS="$4"
checkSUM="$5"
xmode="$6"
prefix=mainloop1
prefixt=mainloop2
[[ "$7" = "batch2" ]] && prefix=mainloop3 && prefixt=mainloop4
SORTCOMPLETE="${atmp}/${prefix}_${RANDOM}$(rand_alpha)$$_tmp.log"
NFS="${atmp}/${prefixt}_${RANDOM}$(rand_alpha)$$_tmp.log"
sblk $IN $SORTCOMPLETE $NFS $xmode
#files=("$@") ; for x in "${files[@]}"; do sblk $xmode $OUTPUT $NFS; done

