#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/save-changesnewfnts
fmt="%Y-%m-%d %H:%M:%S"
prefix=mainloop1
prefixt=mainloop2
prefixth=cache1
atmp="$1"
SORTCOMPLETE="$2"
NFS="$3"
checkSUM="$4"
checkMETHOD="$5"
# [[ "$5" = "batch2" ]] && prefix=mainloop3 && prefixt=mainloop4 && prefixth=cache2  # $4  # if interleaving
debug_log="$6"
debug_file="$7"

shift 7
is_sum="false"
get_hashmethod "profileloop"

## $atmp "false" "main" "batch2"
# SORTCOMPLETE="${atmp}/${prefix}_${RANDOM}$(rand_alpha)$$_tmp.log"  # if interleaving
# NFS="${atmp}/${prefixt}_${RANDOM}$(rand_alpha)$$_tmp.log"  # if interleaving
## CACHE="${atmp}/${prefixth}_${RANDOM}$(rand_alpha)$$_tmp.log"

for f in "$@"; do
    rblk "$f" $SORTCOMPLETE $NFS $checkSUM $debug_log $debug_file
done
