#!/usr/bin/env bash
# supress output helper script to launch inotifywait optional logging   01/13/2026
#nohup /usr/local/save-changesnew/inotify "$@" > /dev/null 2>&1 &
fmt="%Y-%m-%d %H:%M:%S"
log_date=$(date +"$fmt")
echo $log_date > /tmp/inotify.log
nohup /usr/local/save-changesnew/inotify "$@" >> /tmp/inotify.log 2>&1 &
echo $! > /tmp/inotify_watcher.pid
