#!/bin/bash
atmp="$1"
folder="$2"
tout="${atmp}/searchfiles1_$$_tmp.log"  # create temp output file path using current PID
shift 2

files=("$@")

for f in "${files[@]}"; do
    # Assuming $folder is globally defined or passed in, or adapt as needed
    t="${f#"$folder"}"
    printf "%s\0" "$t" >> "$tout"
done
