#!/bin/bash
. /usr/local/save-changesnew/rntchangesfunctions
. /usr/local/save-changesnew/save-changesnewfnts
atmp="$1"
folder="$3"
pf="$4" #Prefix
tout="${atmp}/${pf}1_${RANDOM}$(rand_alpha)$$_tmp.log"  # create temp output file path using current PID
while read -r -d '' x; do
    y="${x#"$folder"}"
	y="$( escf "$y")"
    printf "%s\0" "$y" >> "$tout"
done < $2
