#!/bin/bash
get_vrn(){
if [ "$1" = "-v" ]; then
   echo "version 5.0"
   echo
   echo "recentchanges aka Developer buddy"
   echo
   exit
elif [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] ; then
   echo "version 5.0"
   echo
   echo "recentchanges aka Developer buddy"
   echo
   echo "Makes an xzm of all changes 5 minutes or newer. A manifest will be included as well as a pull transfer"
   echo "log. These will be sent to   /tmp    as   rntchanges.xzm  ect"
   echo
   echo "Useful if you compiled a program you can ie specify recent changes 5 to pull all new files 5 seconds"
   echo "or newer"
   echo
   echo "Modes available Search or SRC or Query See bottom after usage how to use modes"
   echo
   echo
   echo "recentchanges s         where s is time in seconds"
   echo
   echo -e "usage:    recentchanges \t\t grab all files 5 minutes or new		these will include system search as well"
   echo -e "usage:    recentchanges 30	\t grab all files 30 seconds or newer"
   echo
   echo
   echo "Modes"
   echo
   echo "Search        for just a system search"
   echo
   echo -e "recentchanges search \t\t search for files 5 minutes or newer"
   echo -e "recentchanges search 30 \t search for files 30 seconds or newer"
   echo
   echo "Search for files newer than a file or directory"
   echo
   echo "recentchanges search /home/guest/myfile.txt    search for files newer than myfile"
   echo "recentchanges search myfile.txt"
   echo "recentchanges search /home/guest/My\ Directory\ two/with\ spaces/   ... newer than directory"
   echo
   echo
   echo "SRC"
   echo
   echo -e "recentchanges SRC \t\t  Target a root directory. Useful if you compiled an application."
   echo
   echo     " examples:"
   echo     " recentchanges 60 SRC"
   echo     " recentchanges SRC 180"
   echo
   echo
   echo " This feature will package an application with a cuztomized name into an .xzm"
   echo " It allows to focus the search and exclude even files that made it past the filter."
   echo " This was the main intent of the concept of recentchanges and everything is fully automatic"
   echo
   echo " Note: when using this feature ensure that you know there is a parent directory with files in it"
   echo " as well its most useful within a definite peroid of time. The fact that a large amount of files went"
   echo " to one directory allow this to be possible. If for some reason it doesnt work use recentchanges to make rntfiles.xzm"
   echo
   echo "Query"
   echo
   echo "Find out information about files from searches. backend set to default will use query script. database uses query.py"
   echo "ANALYTICS uses logs from /tmp and with a seperate set of heuristics. STATPST is from logs and stats in .gpgs"
   echo
   echo "Inverse the search with Symlink"
   echo
   echo -e "rnt \t\t same as `recentchanges` \t output /tmp"
   echo -e "rnt search 30 \t search for filtered files 30 seconds or newer\t output /Downloads"
   echo -e "rnt search myfile.txt \t      search for unfiltered files newer than myfile."
   echo -e "rnt SRC or rnt 30 SRC \t make .xzm of compiled app or root"
   echo
   echo  "Backup"
   echo " set isolateBACK to true and call 'savechanges-new backup' for Changes=EXIT:/"
   echo " save-changesnew for Changes="

   exit
fi
exit 1
}

