#!/bin/bash
#      recentchanges search        filtered     recentchanges v3.0    08/01/2025
if [ `whoami` != "root" ]; then
	echo "Please enter your root password below"
	if [ "$1" == "search" ]; then echo "usage rnt 60, rnt src rnt 60 src or rnt myfile" && exit; fi
    if [ "$1" == "query" ] || [ "$1" == "SRC" ] || [ "$1" == "src" ]; then
        argone=$1
		argtwo=$2
		if [ -z "$argtwo" ]; then argtwo="noarguser"; fi
	else
        argone="search"
        argtwo="$1"
    fi
	if [ "$2" == "SRC" ] || [ "$2" == "src" ]; then
		argone=$2
		argtwo=$1	
	fi    
    su - -c "/usr/local/save-changesnew/filteredsearch $argone '$argtwo' `whoami` '$PWD'"
    exit
fi
USR=$3 ; dir="$4"
if [ "$3" == "" ] || [ "$4" == "" ]; then USR="guest"; dir="$PWD"; fi
test -d "$dir" || { echo  "not a valid directory. usage rnt search time."; exit 1; }
if  ! id $3 >/dev/null 2>&1; then  echo "user:" ${3} "not found"; exit 1 ; fi
THETIME=$2
if [ "$2" == "" ]; then
    THETIME=$1
    if [ "$1" != "" ]; then
        if [ "$1" == "query" ]; then
            THETIME="noarguser"
        elif [ "$1" == "SRC" ] || [ "$1" == "src" ]; then
            THETIME="$2"
			if [ "$2" == "" ]; then THETIME="noarguser"; fi
        else   
            if ! [ "$1" -ge 0 ] 2>/dev/null; then
	            test -f "$1" || { test -d "$1" || echo echo usage rct or rct time  in seconds or rct file. no such directory file or integer; exit 1; }
            fi
        fi
    else
        THETIME="noarguser"
    fi
	if [ "$2" == "SRC" ] || [ "$2" == "src" ]; then
		THETIME=$1
	fi
fi 	
if [ "$1" == "query" ]; then
    /usr/local/bin/recentchanges query "$THETIME" $USR "$dir"
elif [ "$1" == "SRC" ] || [ "$2" == "SRC" ] ; then
    /usr/local/bin/recentchanges "$1" "$THETIME" $USR "$dir"
else
    /usr/local/bin/recentchanges search "$THETIME" $USR "$dir" filtered
fi
